[WIP] sociallogin integration, personal information form
diaristando/diaristando.app pull request #26
Opened 2024-09-06 20:28 UTC by fsaantiago

## Descrição
 *Descreva brevemente suas mudanças*

## Atividades Relacionadas
*Cole o link de outros PRs abertos, cards ou qualquer outra atividade relacionada.*  

## Tipo de Mudança

- [ ] Bugfix
- [x] Nova funcionalidade
- [x] Alteração de funcionalidade existente
- [x] Refatoração de código
- [ ] Atualização de documentação 
- [ ] Outros

## Passos para Testar

Login Social

Conecte-se ao aplicativo utilizando o e-mail do Google (esta tela se chama `SocialLogin`) e verifique o redirecionamento para a tela de cadastro chamada `PersonalInfo`. A tela precisa se redirecionar para `Signup`, onde possui a chamada de tela 

Anteriormente esta tela funcionava como um login comum mas não possuía uma para se redirecionar.

1. Digite `npx expo start` e depois pressione o botão `Enter`
2. Pressione: `s` -> `a`
3. Ao carregar o aplicativo pressione o botão `Login Social`
![image](https://github.com/user-attachments/assets/c4c053dc-6529-4c5d-a5a5-45ecf3eb13f9)

4. Se conecte na `conta de e-mail` pertencente à `Google`
![image](https://github.com/user-attachments/assets/c93b4ab7-d001-4cf0-93c9-22b58680e586)

5. Selecione uma das opções disponíveis e se conecte à conta:
![image](https://github.com/user-attachments/assets/44294e68-0097-46fa-b29c-314930716939)

6. Clique em continuar para prosseguir com o login:
![image](https://github.com/user-attachments/assets/1fe08a29-22b5-479c-95b5-ce536357d855)

7. Ao se conectar, precisa receber uma mensagem de confirmação:
![image](https://github.com/user-attachments/assets/065c0f5a-e747-4787-9d91-5a38fcf3d381)

## Comentários Adicionais

Atualmente esta tela só se redireciona para a tela de `Home`, mas o correto é que ele siga para a tela de cadastro para que o mesmo tenha suas informações complementares.

![image](https://github.com/user-attachments/assets/3b198ef9-6bc7-414c-abc4-ca118f09d3da)

2024-09-09 20:16 UTC, fsaantiago reviewed
Realizadas as alterações de acordo com o que o Codacy solicitou.
Caso tenha mais alguma alteração estou à disposição!

Fernando Santiago

2024-09-09 21:42 UTC, nicaloribeiro requested changes
Ajustar pontos comentados

2024-09-09 21:42 UTC, nicaloribeiro commented on Diaristando/package.json
> +    "type": "module",
Mova o "type": "module" pra fora do objeto de "scripts"

2024-09-09 21:42 UTC, nicaloribeiro commented on Diaristando/src/components/StepSignup/BankInfo.tsx
> +      keyboardVerticalOffset={100} // Ajuste a altura conforme necessário
Remover comentário

2024-09-09 21:42 UTC, nicaloribeiro commented on Diaristando/src/components/StepSignup/PersonalInfo.tsx
> +          handleChange,
Os pontos do Codacy são aqui. Tem algum espaçamento que ele está identificando.

2024-09-09 21:42 UTC, nicaloribeiro commented on Diaristando/src/components/StepSignup/PersonalInfo.tsx
> +              {/* Formulário */}
Remover comentários

2024-09-09 21:42 UTC, nicaloribeiro commented on Diaristando/src/components/StepsIndicator/Step/StepIndicator.tsx
> +              className={`text-lg font-bold ${
Arqui também o Codacy está identificando uma quebra de linha

2024-09-09 21:42 UTC, nicaloribeiro commented on Diaristando/src/screens/LoginScreen/Signup.tsx
> +      {/* Usamos o componente StepIndicator com 2 etapas */}
Remover comentários

2024-09-10 21:10 UTC, fsaantiago reviewed
As alterações foram feitas no commit conforme solicitado.
Caso tenha mais alguma necessidade de alteração estou à disposição.

2024-09-10 22:02 UTC, nicaloribeiro commented
Tela atual:

<img width="411" alt="image" src="https://github.com/user-attachments/assets/6e7e7452-9424-4e3d-b544-cdfc5e268178">

Tela do Figma:
<img width="342" alt="image" src="https://github.com/user-attachments/assets/e44d5974-7c34-47bd-8404-0c6ab67543d5">

Ajustes solicitados:
- Verificar questão das cores nas fontes;
- Input desabilitado não está conforme o protótipo;
- Data de Nascimento -> colocar calendário para seleção da data;
- Telefome -> Colocar seelct do DDD;
- Select do gênero com tamanho divergente;
- Verificar máscaras de telefone e cpf;

Pontos levantados em testes de produto:
- Telefone : consegui colocar sem o nove inicialmente;
- Data de nascimento: consegui colocar fora do padrão XX/XX/XXXX
- CEP consegui colocar sem o padrão XXXXX-XXX

2024-09-13 21:52 UTC, nicaloribeiro approved these changes

2024-09-13 21:52 UTC, merged