Feature/store informacoes usuario
diaristando/diaristando.app pull request #27
Opened 2024-09-20 02:32 UTC by fsaantiago

## Descrição

[[DIA-1034](https://app.clickup.com/t/9013198100/DIA-1034)]Configuração Redux e Adaptação do código à biblioteca

## Tipo de Mudança

- [ ] Bugfix
- [X] Nova funcionalidade
- [X] Alteração de funcionalidade existente
- [ ] Refatoração de código
- [ ] Atualização de documentação
- [ ] Outros

## Passos para Testar

Antes de iniciar os testes instale a biblioteca do Redux com o comando:

```
npm install @reduxjs/toolkit react-redux
```

## Comentários Adicionais
Alterações realizadas em:
- [PersonalInfo.tsx](https://github.com/diaristando/diaristando.app/blob/feature/store-informacoes-usuario/Diaristando/src/components/StepSignup/PersonalInfo.tsx)
- [App.tsx](https://github.com/diaristando/diaristando.app/blob/feature/store-informacoes-usuario/Diaristando/App.tsx)

2024-09-20 19:50 UTC, nicaloribeiro requested changes

2024-09-20 19:50 UTC, nicaloribeiro commented on Diaristando/src/components/StepSignup/PersonalInfo.tsx
> +          setUser({
- Aqui você pode passar o "**payload**" **diretamente** para o "**setUser**". Como os **campos** seguem o **mesmo nome**, não é necessário "re-declarar" como feito. O ideal é **tipar** "payload" com a mesma interface usada na Store para ser possível identificar o que está sendo passado. 
- Outro ponto é a questão do ddd, ele **não** precisa ser um **campo separado**, ele vai ser concatenado ao telefone e a string ficará "ddd+telefone". O backend irá receber a string completa.
- No destructuring feito em "const { ddd, telefone, ...rest } = values;", o "rest" terá todos os atributos do formulário **exceto** **ddd** e **telefone** ( que foram extraídos ). Por isso no trecho 
`const payload = {
          ...rest,
          telefone: phoneWithDdd
}`  o payload o telefone foi adicionado, o "rest" está sem ele ( pois sofreu destructuring anteriormente ) e foi adicionado da maneira que precisamos (ddd+telefone).

2024-09-20 19:50 UTC, nicaloribeiro commented on Diaristando/src/store/slices/userSlice.tsx
> +  ddd: string;
Não precisa do atributo "ddd", ele será concatenado ao "telefone".

2024-09-20 19:50 UTC, nicaloribeiro commented on Diaristando/src/store/slices/userSlice.tsx
> +  nomeSocial?: string;
Deixar "genero" como campo obrigatório e criar enum:
`enum Genero {
FEMININO,
MASCULINO,
NAO_BINARIO
}`

2024-09-24 20:48 UTC, fsaantiago commented on Diaristando/src/store/slices/userSlice.tsx
> +  nomeSocial?: string;
Alterações realizadas.

2024-09-24 20:49 UTC, fsaantiago commented on Diaristando/src/store/slices/userSlice.tsx
> +  ddd: string;
Atributo "ddd" retirado. Agora o telefone é inserido corretamente mesmo sem o campo declarado de forma explícita.

2024-09-24 20:49 UTC, fsaantiago commented on Diaristando/src/components/StepSignup/PersonalInfo.tsx
> +          setUser({
Enxuguei o código como sugerido. Obrigado pela observação.

2024-09-25 18:22 UTC, nicaloribeiro requested changes

2024-09-25 18:22 UTC, nicaloribeiro commented on Diaristando/src/components/StepSignup/PersonalInfo.tsx
> +        const phoneWithDdd = `{telefone}`;
Há um problema em "const phoneWithDdd = `{telefone}`;
Dessa forma, o valor está ficando literalmente a String.
<img width="207" alt="image" src="https://github.com/user-attachments/assets/967650fd-97e2-409b-869c-7d11bf902791">

É necessário utilizar template String, como estava antes: const phoneWithDdd = `${values.ddd}${values.telefone}`;
Dessa forma, a string final é formada com os valores das variáveis que estão dentro ${}.
Então, `${values.ddd}${values.telefone}` ficaria `1199990000`.

2024-09-25 18:22 UTC, nicaloribeiro commented on Diaristando/src/components/StepSignup/PersonalInfo.tsx
>          nomeSocial: '',
É necessário voltar com o atributo "ddd" initial values. Ele ainda é um campo do formulário, mas ao salvar as informacoes ele é concatenado com o telefone.

2024-10-01 01:17 UTC, nicaloribeiro approved these changes

2024-10-01 01:17 UTC, merged